version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobtracker-db
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: jobtracker-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: jobtracker-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
        - postgres
        - redis
